### ISSUE TITLE
add this meta line to your head

### ISSUE THREAD

**Issue by rimmesbe** [hirsi911/f1-3-c2p1-colmar-academy#1]
This is an important line to add in the `<head>` section whenever you are using media queries. It makes sure your media queries register on all devices.
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

https://github.com/hirsi911/f1-3-c2p1-colmar-academy/blob/master/Colmar/index.html#L3

**Comment by hirsi911** [comment]
This is done - thank you.
