### ISSUE TITLE
class naming conventions

### ISSUE THREAD

**Issue by rimmesbe** [hirsi911/f1-3-c2p1-colmar-academy#2]
Try to avoid using class names with order numbers and positional locations like: left-banner, banner-1, banner-2
This makes your classes dependent on order and position, and less reusable. In reality websites update and move around a lot and you want your code to be flexible. Take a look at the BEM convention which may help you understand a good naming convention.
http://getbem.com/introduction/

https://github.com/hirsi911/f1-3-c2p1-colmar-academy/blob/master/Colmar/index.html#L54-L55

**Comment by hirsi911** [comment]
ok, fair point. Typical beginner fault, I think :)
