### ISSUE TITLE
html5 semantic tags

### ISSUE THREAD

**Issue by rimmesbe** [hirsi911/f1-3-c2p1-colmar-academy#3]
I really like that you are using some semantic tags, but there are many more. They are very popular in modern html development so worth looking into.
https://github.com/hirsi911/f1-3-c2p1-colmar-academy/blob/master/Colmar/index.html#L189

https://www.pluralsight.com/guides/html-css/semantic-html?aid=701j0000001heIqAAI&promo=&oid=&utm_source=google&utm_medium=ppc&utm_campaign=CA_Dynamic&utm_content=&utm_term=&gclid=CjwKCAjwlrnNBRBMEiwApKU4PBiUM7wtxiyqNw-6Zoikh6ChlNul6tTL839Zj2h_JNTZcK6PE5WWlRoCiOYQAvD_BwE

**Comment by hirsi911** [comment]
Thank you for this article - really interesting!
