### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [hirsi911/f1-3-c2p1-colmar-academy#5]
Grade: exceeds expectations

Summary: Nice job on this project the site looks really good on both mobile and desktop. Your code is  very organized and you used a lot of good techniques. Take a look at the issues I created as they will introduce you to some new techniques and conventions you should adopt. The biggest issue is the class naming convention. There are many official css naming convention out there. Like I said I like BEM but see which one you like and adopt it.
Good job, hope you enjoyed the course!

**Comment by hirsi911** [comment]
Thank you! I still feel at the very beginning...
